# Generated by Django 2.2.12 on 2022-03-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coche', '0001_initial'),
        ('marca', '0001_initial'),
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='marca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marca.Marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='coche',
            name='modelo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelo.Modelo', verbose_name='Modelo'),
        ),
    ]
