# Generated by Django 2.2.12 on 2022-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coche', '0002_auto_20220316_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='modelo',
            field=models.OneToOneField(on_delete=models.SET('None'), to='modelo.Modelo', verbose_name='Modelo'),
        ),
    ]
