# Generated by Django 2.2.12 on 2022-03-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coche', '0003_auto_20220316_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='modelo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelo.Modelo', verbose_name='Modelo'),
        ),
    ]
