# Generated by Django 2.2.12 on 2022-03-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coche', '0004_auto_20220316_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marca.Marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Modelo', verbose_name='Modelo'),
        ),
    ]
