# Generated by Django 2.2.12 on 2022-03-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coche', '0005_auto_20220316_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.Marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelo.Modelo', verbose_name='Modelo'),
        ),
    ]
