# Generated by Django 2.2.12 on 2022-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='modelos',
            field=models.ManyToManyField(blank=True, related_name='modelo', to='modelo.Modelo', verbose_name='Modelos'),
        ),
    ]
