# Generated by Django 2.2.12 on 2022-03-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coche', '0001_initial'),
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Modelo')),
                ('carroceria', models.CharField(choices=[('0', 'Sedán'), ('1', 'Familiar'), ('2', 'Coupé'), ('3', 'Todoterreno'), ('4', 'Descapotable'), ('5', 'SUV')], max_length=1, verbose_name='Carroceria')),
                ('coches', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coche', to='coche.Coche', verbose_name='Coches')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marca.Marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['id'],
            },
        ),
    ]
